### ISSUE TITLE
Run Simulation

### ISSUE THREAD

**Issue by whiteyhat** [gdistasi/LNSim#1]
Hi, How can I run a simulation? I have tried it in the readme but nothing happen

**Comment by whiteyhat** [comment]
I see this is not maintained anymore

**Comment by gdistasi** [comment]
Sorry,
it is maintained. What do you plan to achieve?

Best regards,
GIovanni

**Comment by s-tikhomirov** [comment]
I think the question was on how to install it. I'm also looking for this information and don't see it in the readme. Running `make` gives me
```
g++-4.9 -std=c++11  -c main.cpp -o main.o 
make: g++-4.9: Command not found
makefile:19: recipe for target 'main.o' failed
make: *** [main.o] Error 127
```

However when I modify the `makefile` replacing
```
GPP = g++-4.9
```
with
```
GPP = g++
```
and  run
```
make
```
it compiles.

Is there a reason that the compiler is fixed at quite an old version? (My Ubuntu 18.04 includes g++ 7.4.0)?

**Comment by whiteyhat** [comment]
I created my own simulation from scratch when I found this repo did not have proper documentation
https://github.com/whiteyhat/Lightning-Network-Simulator

**Comment by s-tikhomirov** [comment]
That's the spirit, @whiteyhat ! :) Looking into your simulator for my research as well, excellent work!
