### ISSUE TITLE
Add launch instructions as --help

### ISSUE THREAD

**Issue by s-tikhomirov** [gdistasi/LNSim#4]
Currently, the instruction on what all the parameters mean are only given in the README. Making the tool itself display usage instructions on `--help` command would be really helpful. On a related node, on launching without arguments it could display help (or something like "launch with --help to see usage instructions") instead of launching a simulation with 0 channels.

**Comment by gdistasi** [comment]
Very appropriate suggestion... I will try to improve as suggested as soon as possible. Thanks.

**Comment by gdistasi** [comment]
Sources updated.
